name = "tmkdo"
type = "javascript"
compatibility_date = "2024-12-10"

[env.production]
name = "tmkdo-prod"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

