name = "tmkdo"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".cloudflare"

[env.production]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
